// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: proto/order/order.proto

package order

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	OrderTracking_SubscribeToOrderUpdates_FullMethodName = "/order.OrderTracking/SubscribeToOrderUpdates"
)

// OrderTrackingClient is the client API for OrderTracking service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OrderTrackingClient interface {
	// Server-side streaming for real-time updates [cite: 173]
	SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (OrderTracking_SubscribeToOrderUpdatesClient, error)
}

type orderTrackingClient struct {
	cc grpc.ClientConnInterface
}

func NewOrderTrackingClient(cc grpc.ClientConnInterface) OrderTrackingClient {
	return &orderTrackingClient{cc}
}

func (c *orderTrackingClient) SubscribeToOrderUpdates(ctx context.Context, in *OrderRequest, opts ...grpc.CallOption) (OrderTracking_SubscribeToOrderUpdatesClient, error) {
	stream, err := c.cc.NewStream(ctx, &OrderTracking_ServiceDesc.Streams[0], OrderTracking_SubscribeToOrderUpdates_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &orderTrackingSubscribeToOrderUpdatesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type OrderTracking_SubscribeToOrderUpdatesClient interface {
	Recv() (*OrderStatusUpdate, error)
	grpc.ClientStream
}

type orderTrackingSubscribeToOrderUpdatesClient struct {
	grpc.ClientStream
}

func (x *orderTrackingSubscribeToOrderUpdatesClient) Recv() (*OrderStatusUpdate, error) {
	m := new(OrderStatusUpdate)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// OrderTrackingServer is the server API for OrderTracking service.
// All implementations must embed UnimplementedOrderTrackingServer
// for forward compatibility
type OrderTrackingServer interface {
	// Server-side streaming for real-time updates [cite: 173]
	SubscribeToOrderUpdates(*OrderRequest, OrderTracking_SubscribeToOrderUpdatesServer) error
	mustEmbedUnimplementedOrderTrackingServer()
}

// UnimplementedOrderTrackingServer must be embedded to have forward compatible implementations.
type UnimplementedOrderTrackingServer struct {
}

func (UnimplementedOrderTrackingServer) SubscribeToOrderUpdates(*OrderRequest, OrderTracking_SubscribeToOrderUpdatesServer) error {
	return status.Errorf(codes.Unimplemented, "method SubscribeToOrderUpdates not implemented")
}
func (UnimplementedOrderTrackingServer) mustEmbedUnimplementedOrderTrackingServer() {}

// UnsafeOrderTrackingServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OrderTrackingServer will
// result in compilation errors.
type UnsafeOrderTrackingServer interface {
	mustEmbedUnimplementedOrderTrackingServer()
}

func RegisterOrderTrackingServer(s grpc.ServiceRegistrar, srv OrderTrackingServer) {
	s.RegisterService(&OrderTracking_ServiceDesc, srv)
}

func _OrderTracking_SubscribeToOrderUpdates_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(OrderRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OrderTrackingServer).SubscribeToOrderUpdates(m, &orderTrackingSubscribeToOrderUpdatesServer{stream})
}

type OrderTracking_SubscribeToOrderUpdatesServer interface {
	Send(*OrderStatusUpdate) error
	grpc.ServerStream
}

type orderTrackingSubscribeToOrderUpdatesServer struct {
	grpc.ServerStream
}

func (x *orderTrackingSubscribeToOrderUpdatesServer) Send(m *OrderStatusUpdate) error {
	return x.ServerStream.SendMsg(m)
}

// OrderTracking_ServiceDesc is the grpc.ServiceDesc for OrderTracking service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OrderTracking_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "order.OrderTracking",
	HandlerType: (*OrderTrackingServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SubscribeToOrderUpdates",
			Handler:       _OrderTracking_SubscribeToOrderUpdates_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/order/order.proto",
}
